### ISSUE TITLE
🏛️ [EPIC] : Cardano Blockchain Integration

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#10]
### Summary

Provide a stand-alone Rust Crate to interface to cardano block data.

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-8636

### Description

Cardano Blockchain Integration

Provide a standalone Rust Crate with the following features:

The Library does not provide any persistence of block data from a node.
Does not execute plutus or validate ledger state, only that the Blockchain is intact and the blocks are properly formatted.

All node data structures and low level communications is to be provided by this library:
https://github.com/txpipe/pallas
Anything we need to add in regard to low level cardano data and functions MUST be added to this library and contributed upstream, not embedded into our own library.

Node communications documentation: 
https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec/

txPipe have an implementation of reading immutable data from the Cardano Node/Mithril snapshot here:
https://github.com/txpipe/pallas/pull/328

### Phase 1

- [x] #11
- [x] #12
  - [x] Configuration
    - [x]  Specify the upstream node address for the N2N protocol only.
- [x] #42 
- [x] Tell the follower where to follow from (Specific slot#, or Genesis block, or Tip)
- [x] Validate each block based on block structure for a given era.
- [x] Client retrieves blocks over a client provided queue (multithreaded MPSC).
  - [x] Queue items can be:
    - [x] Next Block
    - [x] Rollback
    - [x] Node communications error
- [x] #63

### Phase 2

- [x] Ability through the API to retrieve an arbitrary Block from a node.
- [x] Basic inter-block validity checks. Validate each block is consecutive, based on known data for the previous block.
- [x] API call which can validate an arbitrary block.
- [x] API call which can iterate a block and return data for individual transactions from the block.

### Phase 3

- [x] Documented WASM API Definition with all the API calls supplied by the Follower Crate defined.
- [x] Interface to Webasm Runtime
- [x] Generate Hermes events for each blockchain event.
- [x] Hermes interface for block/transaction data stream.
- [x] Hermes integration test cases

### Mithril snapshot support enhancement
- [x] Configuration option pointing to storage of a mithril snapshot of blockchain data.
- [x] #50
  - [x] If provided the library returns block from the snapshot if they exist, in preference to reading blocks from the node.
