### ISSUE TITLE
🏛️ [EPIC] : Hermes application packaging and local file manager

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#129]
### Summary

Secure and sandboxed application package and local file manager.

### JIRA Epic

TODO

### Description

Applications in Hermes will be composed of a number of files. Applications will also need access to sand-boxed and secure generalized file data storage. This module delivers the file management APIs used both internally by Hermes, and the Applications running on Hermes themselves.

Functionality will:

1. Load Hermes Application Packages
2. Check Applications are properly signed by trusted keys.
3. Find metadata within the Application Package.
4. Find Data within the Application Package.
5. Create and Sign Application Packages from individual files.
6. Create and manage sandboxed file storage for each application.
7. Expose an API to the WASM Modules to Create/Delete/Read/Write/Update files.

Define the layout of a Hermes Application Package, and the required metadata, configuration, static data, and WASM modules they must contain.

The Hermes Application Package is based on HDF5, an open format and is able to be supported by third party developers.

### TODO

- [x] #70
- [x] #159
  - [ ] Define Metadata storage
  - [ ] UX directly served files.
  - [ ] RO Data files
  - [ ] WASM Modules
- [x] Configuration to store trusted public keys.
   - [x] https://github.com/input-output-hk/hermes/issues/263
- [ ] Create and Sign Hermes application packages.
   - [x] #234
   - [x] #249
   - [x] #237 
   - [x] #270
- [x] #292
- [x] https://github.com/input-output-hk/hermes/issues/308
- [x]  https://github.com/input-output-hk/hermes/issues/280
