### ISSUE TITLE
🏛️ [EPIC] : HTTP Gateway.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#130]
### Summary

HTTP Gateway for Frontend UX and Business logic API access for apps.

### JIRA Epic

TODO

### Description

Hermes will deliver its UX via a built-in HTTP Gateway which will allow industry standard web development tools to deliver fully distributed UX. This is an internal module of the Hermes engine.

Functionality will:

1. Listen on a configurable port for HTTP connections from local Web clients.
2. Route traffic to Hermes packaged applications via their subdomains.
3. Properly respond to CORS requests.
4. For regex defined paths, generate events to validate authorization to access a particular resource.
5. Serve static data directly from the application package if it matches the requested path for a GET Method.
6. Direct all other requests to the Application Webasm as HTTP Events for dynamic processing.

This is a core module integral to basic Hermes functionality, but it does have an interface that operates like a runtime extension.  It also has direct access through the sandboxed filesystem APIs without sending all requests through the event subsystem,

### TODO

- [x] Documented WASI API Definition
- [x] Implement core http gateway functionality within hermes.
- [x] Interface to WASM runtime defined API as a runtime extension.
- [x] Automated test cases running in continuous integration.
