### ISSUE TITLE
🏛️ [EPIC] : P2P networking and IPFS Integration.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#131]
### Summary

LibP2P/IPFS Integration as a runtime extension

### JIRA Epic

TODO

### Description

The Hermes nodes will intercommunicate as peers using functionality provided by the LibP2P Library. It will also enable high level distributed functionality provided by IPFS.

Functionality will:

1. Retrieve Data and Files published to IPFS.
2. Pin that data so it can be shared and served to peers.
3. Enable generalized Peer to Peer use of distributed Pub/Sub and Key/Value networking.
    * Enable WASM modules to subscribe to updates on a Pub/Sub topic.
    * Enable Reading the Value from a Key distributed in a Peer to Peer DHT.
4. Validate Values for data published to either a Pub/Sub topic, or the DHT.
    * Allow WASM modules run by Hermes to prove data is valid, and evict misbehaving peers.
5. Generate Events so that WASM run by Hermes can be processed when it updates.

### TODO

- [ ] Documented WASI API Definition
- [ ] Interface to WASM Runtime.
- [ ] Automated Test Cases running in continuous integration.

**Comment by Mr-Leshiy** [comment]
Work related to the M3 is done.
