### ISSUE TITLE
🏛️ [EPIC] : Milestone 3 Wrapup

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#132]
### Summary

Deliver Milestone 3 to the community

### JIRA Epic

TODO

### Description

Hermes and Athena will be developed and delivered under an Apache-2 open source license. A public repository will be published in the first month to house this proposal's development. The community can follow along and explore what is being delivered as development progresses.

The community will be free to review and comment on our development work as it occurs. As an open source project, we welcome community contributions to Hermes and Athena.

At each Milestone, we will publish tagged versions of the code base and a test report showing that all the proposed features are correctly built and have been delivered and tested. We will also prepare recorded demonstrations of the completed functionality, as appropriate. A walk through explainer video will be provided.﻿

Sessions will be conducted during the development process to discuss the work completed and ongoing and give the community access to not only check for themselves the work being delivered but to question the development team about the project to allow a better understanding of the system to be fostered between the developers and the community.

### Todo

- [ ] Apache-2 Licenses applied correctly to all code and no license conflicts in any dependent libraries.
- [ ] Repository tagged as at Milestone completion.
- [ ] Test report covering delivered functionality.
- [ ] Public online session and demonstration covering work completed, and allow community feedback within the forum.

### Dependencies

- [x] #128 
- [x] #129 
- [x] #130 
- [x] #131
