### ISSUE TITLE
🏛️ [EPIC] : Milestone 2 Wrapup

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#133]
### Summary

Deliver Milestone 2 to the community

### JIRA Epic

https://input-output.atlassian.net/browse/NPG-9195

### Description

Hermes Foundational Work will be a minimal implementation of Hermes to incorporate the basic internal APIs that the Athena application will require, such as time; chronological event generation; logging; basic hashing, and basic cryptography functions. Hermes allows the WASM modules it runs to call these APIs. Still, the runtime will be highly simplified only to allow testing of the APIs. The APIs created in this milestone will be documented for ease of use by any application developer designing programs to run on the Hermes Application Engine.

It will also include a Rust implementation of a basic Cardano Node follower and its integration into the Hermes node. This follower will only supply the necessary features required to deliver Project Catalyst Voting for Athena and will serve as the basis for future features that are out of scope for this proposal but which would enhance Cardano Integration, generally.

Hermes and Athena will be developed and delivered under an Apache-2 open source license. A public repository will be published in the first month to house this proposal's development. The community can follow along and explore what is being delivered as development progresses.

The community will be free to review and comment on our development work as it occurs. As an open source project, we welcome community contributions to Hermes and Athena.

At each Milestone, we will publish tagged versions of the code base and a test report showing that all the proposed features are correctly built and have been delivered and tested. We will also prepare recorded demonstrations of the completed functionality, as appropriate

Sessions will be conducted during the development process to discuss the work completed and ongoing and give the community access to not only check for themselves the work being delivered but to question the development team about the project to allow a better understanding of the system to be fostered between the developers and the community.

### Todo

- [x] Apache-2 Licenses applied correctly to all code and no license conflicts in any dependent libraries.
- [x] Repository tagged as at Milestone completion.
- [x] Test report covering delivered functionality.
    * https://github.com/input-output-hk/hermes/actions/runs/8610164478
- [x] Public online session and demonstration covering work completed, and allow community feedback within the forum.
    * https://github.com/input-output-hk/hermes/discussions/207

### Dependencies

- [x] #10
- [x] #14 
- [x] #64
