### ISSUE TITLE
🏛️ [EPIC] : Hermes Module - Voter Registration tracking for Athena

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#134]
### Summary

Write a Hermes WASM Module that tracks voter registrations on chain.

### JIRA Epic

TODO

### Description

This Hermes module for Athena application will track Catalyst voter registrations from transaction events detected on the Cardano blockchain and save that data in a local database. 

This is a set of WASM Modules deployed via the Athena application package, and run by the Hermes Application Engine.

Functionality will:

1- Process transaction events from the Cardano Blockchain in real time.
2- Detect and validate project Catalyst voter registrations.
3- Store registration data in a local database.
4- Enable registrations to be queried through the Hermes HTTP gateway. (Rest API)
5- In the scope of this proposal, Athena only tracks Voter Registration, and does not manage representatives, or other registration types.
6- Handle rollbacks correctly, and ensure that all recorded registrations are correct as at the current block processed from the blockchain.

### TODO

- [ ] Connect to database on application load and setup or migrate DB schema.
- [ ] Process transactions and detect voter registration type transactions.
  - [ ] Record registration data in the database.
- [ ] Handle on-chain rollbacks
- [ ] API Endpoint to query and report voter registration information.
- [ ] API Endpoint to report status of data storage (Is it syncing or following from Tip?)

**Comment by rafal-ch** [comment]
We have a fully functional module that tracks voter registrations on chain. Closing the issue.
