### ISSUE TITLE
🏛️ [EPIC] : Functionally Complete Hermes

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#147]
### Summary

Finalizing the Hermes WASM execution engine (MVP)

### JIRA Epic

TODO

### Description

Hermes - Functionally complete

This Epic involves final integration of the Hermes runtime and running a real sample application on top of it.  To validate the engine architecture and ensure it operates as expected for the MVP initial state.

### Features

- [ ] Handle and orchestrate a pool of WASM executors that execute the packaged application’s business logic.
- [ ] Load WASM modules for a packaged application.
- [ ] Execute an init function provided by each WASM module.
- [ ] Given an event to be delivered to a packaged application:
  - [ ] Get all the WASM Modules for the application that processes that event.
  - [ ] Schedule those modules on free WASM executors from the pool.
  - [ ] Clone the WASM memory state before execution.
  - [ ] Ensures a packaged applications configuration and context are maintained during the lifetime of a WASM Events execution.
- [ ] Automated test cases running in continuous integration.

**Comment by rafal-ch** [comment]
Closing, all sub-issues are done.
