### ISSUE TITLE
🏛️ [EPIC] : Athena - Registration Tracking

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#148]
### Summary

Athena application modules required for tracking on-chain voter registrations.

### JIRA Epic

TODO

### Description

A set of WASM Modules deployed via the Athena application package, and run by the Hermes Application Engine.

### TODO

- [ ] Process transaction events from the Cardano Blockchain in real time.
- [ ] Detect and validate project Catalyst voter registrations.
- [ ] Store registration data in a local database.
- [ ] Enable registrations to be queried through the Hermes HTTP gateway. (Rest API)
  - [ ] Only tracks Voter Registration, and does not manage representatives, or other registration types.
- [ ] Handle rollbacks correctly, and ensure that all recorded registrations are correct as at the current block processed from the blockchain.
