### ISSUE TITLE
Hermes Module - Voting Power Calculation for Athena

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#149]
### Summary

Record and Calculate voting power for registered voters from direct block data

### JIRA Epic

TODO

### Description

A set of Athena modules that process block data from cardano and record staked ADA and unpaid rewards, so that voting power can be properly recorded and calculated for any registered voter or known stake address.

### Todo

- [ ] Read ledger state in real time from the Cardano Blockchain block data.
- [ ] Calculate and record staked ADA balances for registered voters into the applications database.
- [ ] Handle rollbacks correctly, and ensure that all recorded registrations are correct as at the current block processed from the blockchain.
- [ ] Recover Cardano blockchain following from the last scanned state.
- [ ] Enable staked ADA and Voting power to be queried through the Hermes HTTP gateway. (Rest API)
