### ISSUE TITLE
🏛️ [EPIC] : Hermes Module - P2P Distribution of Voting Event Database for Athena

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#153]
### Summary

P2P distribution of the Voting Event Database

### JIRA Epic

TODO

### Description

Including an API where a local application can query the latest Catalyst Voting event data without reliance on a central server.

Functionality will:

* Subscribe to a Pub/Sub channel which alerts to updates to updates to Catalyst Voting Event Data.
* Retrieve the latest Catalyst Event Data from IPFS, based on the update event received.
* Update the data stored in the local database.
* Serve a copy of the latest data to distributed peers.
* Provide dynamic endpoints that allow Catalyst Event data to be queried to enable voting on the current Fund.
* Validate the data has been authoritatively published by a trusted source.
* Allow the Athena user to customize which source of event data they trust.

### Hermes Modules

- [ ] Module that subscribes to a fund specific channel and processes updates to catalyst voting event data.
- [ ] Module that retrieves updated data from IPFS and updates that data in a local database.
- [ ] Module which provides an API to allow event data to be queried by the Athena front end.
- [ ] Config to allow Athena user to customize the source of event data they trust.

**Comment by rafal-ch** [comment]
@stevenj will refine this a bit
