### ISSUE TITLE
🏛️ [EPIC] : Hermes Module - Catalyst Ballot Box - for Athena

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/hermes#155]
### Summary

Catalyst Ballot Box

### JIRA Epic

TODO

### Description

Hermes Module for Athena to provide Catalyst Ballot Box functionality

* Via the Pub/Sub network, save all cast votes in the local DB.
* Provide an API via the Hermes HTTP gateway to:
  * Retrieve Votes that are published
  * Authoritatively publish a receipt that the vote has been recorded securely.
  * Perform an encrypted tally on all recorded votes.
  * Reject votes cast outside the voting window.

### Hermes Modules

- [ ] Database Schema and Vote collection from known Pub/Sub Channel
- [ ] Validate votes cast on the channel are from valid/authoritative voters for the event.
- [ ] Hermes API to perform encrypted tally on the collected votes in the bulletin board.
- [ ] Reject Votes cast before or after the voting window time frame.
